[package]
name = "wumpus-webhook"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
chrono = "0.4.34"
reqwest = "0.11.24"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
shuttle-actix-web = "0.39.0"
shuttle-runtime = "0.39.0"
tokio = "1.26.0"
